const METLIFE_CENTERS = [
  {
    "id": 1,
    "governorate_ar": "الاسكندرية",
    "governorate_en": "Alexandria",
    "city_ar": "الاسكندرية",
    "city_en": "Alexandria",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "127 طريق الحرية - ميدان الشلالات - ناصية شارع فؤاد أمام ساعة الزهور - الدور الخامس",
    "address_en": "127 Al-Horreya Road – Shallalat Square – Corner of Fouad Street, in front of the Flower Clock – 5th Floor",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 31.202822,
    "lng": 29.923346,
    "gmaps": "https://www.google.com/maps?q=31.202822,29.923346"
  },
  {
    "id": 2,
    "governorate_ar": "الاسكندرية",
    "governorate_en": "Alexandria",
    "city_ar": "العجمى",
    "city_en": "Agamy",
    "name_ar": "مركز سبورتنج للعلاج الطبيعى",
    "name_en": "Sporting Physiotherapy Center",
    "address_ar": "ميدان الكيلو 21 طريق اسكندريه مطروح",
    "address_en": "Kilo Square 21 Alex Matrouh Road",
    "phone1": "03 4117036",
    "phone2": "",
    "network": "Orange",
    "lat": 29.944683,
    "lng": 31.22266,
    "gmaps": "https://www.google.com/maps?q=29.944683,31.22266"
  },
  {
    "id": 3,
    "governorate_ar": "الاسكندرية",
    "governorate_en": "Alexandria",
    "city_ar": "سبورتنج",
    "city_en": "Sporting",
    "name_ar": "مركز سبورتنج للعلاج الطبيعى",
    "name_en": "Sporting Physiotherapy Center",
    "address_ar": "175 ش بورسعيد - سبورتنج الصغرى",
    "address_en": "175 Port Said St. - Sporting Al Soghra",
    "phone1": "03 5919323",
    "phone2": "",
    "network": "Orange",
    "lat": 29.775986,
    "lng": 31.10094,
    "gmaps": "https://www.google.com/maps?q=29.775986,31.10094"
  },
  {
    "id": 4,
    "governorate_ar": "الاسكندرية",
    "governorate_en": "Alexandria",
    "city_ar": "سموحة",
    "city_en": "Semouha",
    "name_ar": "مركز الاسكندرية للطب الطبيعى و التاهيل - حياة كير سنتر",
    "name_en": "Alexandria Physical Medicine&Rehabilitation Center - Hayat",
    "address_ar": "طريق 14 مايو - مجمع الوطنية الطبى - سموحه",
    "address_en": "14th of May Road - National Medical Complex - Smouha",
    "phone1": "01098880229",
    "phone2": "03 3856777",
    "network": "Orange",
    "lat": 29.960533,
    "lng": 31.209425,
    "gmaps": "https://www.google.com/maps?q=29.960533,31.209425"
  },
  {
    "id": 5,
    "governorate_ar": "الاسماعيلية",
    "governorate_en": "Ismailia",
    "city_ar": "الاسماعيلية",
    "city_en": "Ismailia",
    "name_ar": "مركز الهدى للعلاج الطبيعى",
    "name_en": "Al Hoda Physiotherapy Center",
    "address_ar": "شارع النخيل اعلى شركة ارامكس للشحن وصيدلية د.احمد عاطف وهبه بجوار مدرسةالطائف",
    "address_en": "El Nakhil Street, above Aramex Shipping Company and Dr. Ahmed Atef Wahba Pharmacy, next to El Taif School",
    "phone1": "01065591010",
    "phone2": "0643222520",
    "network": "Orange",
    "lat": 30.459904,
    "lng": 30.668653,
    "gmaps": "https://www.google.com/maps?q=30.459904,30.668653"
  },
  {
    "id": 6,
    "governorate_ar": "الاسماعيلية",
    "governorate_en": "Ismailia",
    "city_ar": "الاسماعيلية",
    "city_en": "Ismailia",
    "name_ar": "مركز الهدى للعلاج الطبيعى",
    "name_en": "Al Hoda Physiotherapy Center",
    "address_ar": "شارع النخيل – اعلى شركة ارامكس للشحن وصيدلية د.احمد عاطف وهبه بجوار مدرسة الطائف - الاسماعيلية",
    "address_en": "Palm Street – Above Aramex Shipping Company and Dr. Ahmed Atef Wahba Pharmacy, next to Al-Taif School – Ismailia",
    "phone1": "01060055753",
    "phone2": "",
    "network": "Orange",
    "lat": 30.600513,
    "lng": 32.28144,
    "gmaps": "https://www.google.com/maps?q=32.28144,30.600513"
  },
  {
    "id": 7,
    "governorate_ar": "البحيرة",
    "governorate_en": "Beheira",
    "city_ar": "ابو المطامير",
    "city_en": "Abo Al Matameer",
    "name_ar": "المركز التخصصى للعلاج الطبيعى د/ احمد مسعود عبد اللة",
    "name_en": "Dr Ahmed Masoud Abd Allah",
    "address_ar": "بجوار مجمع المحاكم الجديد",
    "address_en": "The new court complex",
    "phone1": "01001283270",
    "phone2": "",
    "network": "Orange",
    "lat": 30.0752,
    "lng": 30.667747,
    "gmaps": "https://www.google.com/maps?q=30.0752,30.667747"
  },
  {
    "id": 8,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الجيزة",
    "city_en": "Giza",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "7 ب ش السد العالى - متفرع من شارع التحرير - اعلى تكا - الدور الرابع",
    "address_en": "7B El Sadd El Aali Street - off Tahrir Street - above Teka - 4th Floor",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.040861,
    "lng": 31.218222,
    "gmaps": "https://www.google.com/maps?q=30.040861,31.218222"
  },
  {
    "id": 9,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الجيزة",
    "city_en": "Giza",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "البوابة الرابعة - ش الخزان - ٢٤٣ ن - أعلى يورو مارشيه - الدور الأول - شقة ٣",
    "address_en": "Hadayek Al Ahram – Gate 4 – Al Khazan Street – Building 243 N – Above Euro Market – First Floor – Apartment 3",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 29.954742,
    "lng": 31.092148,
    "gmaps": "https://www.google.com/maps?q=29.954742,31.092148"
  },
  {
    "id": 10,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الجيزة",
    "city_en": "Giza",
    "name_ar": "مركز النيل التخصصى د/ صلاح عبد المنعم صوان",
    "name_en": "Al Nile Specialized Center For Physical Treatment (Dr. Salah",
    "address_ar": "عمارة النصر - ميدان الجيزة",
    "address_en": "Al-Nasr Building - Giza Square",
    "phone1": "02 35728777 - 02 357",
    "phone2": "01111120054",
    "network": "Orange",
    "lat": 31.21275,
    "lng": 30.061237,
    "gmaps": "https://www.google.com/maps?q=31.21275,30.061237"
  },
  {
    "id": 11,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الدقى",
    "city_en": "Dokki",
    "name_ar": "المركز الذهبى للعلاج الطبيعى",
    "name_en": "Golden Center for Physical Therapy",
    "address_ar": "96شارع التحرير ميدان الدقى - الدقى",
    "address_en": "96 Tahrir Street, Dokki Square - Dokki",
    "phone1": "01015011274",
    "phone2": "",
    "network": "Orange",
    "lat": 31.210476,
    "lng": 30.038258,
    "gmaps": "https://www.google.com/maps?q=31.210476,30.038258"
  },
  {
    "id": 12,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الدقى",
    "city_en": "Dokki",
    "name_ar": "مركز البحراوى للعلاج الطبيعى",
    "name_en": "Dr. Bahrawy Physiotherapy Center",
    "address_ar": "92 ش التحرير – برج ساريدار الطبى – ميدان الدقى",
    "address_en": "92 El Tahrir St., Saridar Medical Tower , Dokki",
    "phone1": "0233362131 - 02 3761",
    "phone2": "01096962233",
    "network": "Orange",
    "lat": 31.214613,
    "lng": 30.038458,
    "gmaps": "https://www.google.com/maps?q=31.214613,30.038458"
  },
  {
    "id": 13,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الدقى",
    "city_en": "Dokki",
    "name_ar": "مركز البرج للعلاج الطبيعى",
    "name_en": "Al borg physiotherapy",
    "address_ar": "14شارع الأنصارى أعلى محطة مترو البحوث - الدقى",
    "address_en": "14 Al-Ansari Street, above Bohouth Metro Station - Dokki",
    "phone1": "02 37619282",
    "phone2": "010 23799940",
    "network": "Orange",
    "lat": 31.209501,
    "lng": 30.05392,
    "gmaps": "https://www.google.com/maps?q=31.209501,30.05392"
  },
  {
    "id": 14,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "السادس من اكتوبر",
    "city_en": "6th October City",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "مدخل جهاز مدينه 6 أكتوبر - امام نادي 6 أكتوبر - عماره رقم 216 - معرض سيارات محمود حمد - الحي السابع - المحور الخلفي",
    "address_en": "Entrance to 6th of October City Authority - Opposite 6th of October Club - Building No. 216 - Mahmoud Hamad Car Showroom - 7th District - Rear Axis",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 29.97998,
    "lng": 30.949656,
    "gmaps": "https://www.google.com/maps?q=29.97998,30.949656"
  },
  {
    "id": 15,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "السادس من اكتوبر",
    "city_en": "6th October City",
    "name_ar": "المركز الذهبى للعلاج الطبيعى",
    "name_en": "Golden Center for Physical Therapy",
    "address_ar": "برج المدينة - بجوار مسجد الحصرى - المحور المركزى - 6 أكتوبر",
    "address_en": "City Tower - Next to Al-Hosary Mosque - Central Axis - 6th of October",
    "phone1": "01005515067",
    "phone2": "",
    "network": "Orange",
    "lat": 30.938854,
    "lng": 29.972355,
    "gmaps": "https://www.google.com/maps?q=30.938854,29.972355"
  },
  {
    "id": 16,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "السادس من اكتوبر",
    "city_en": "6th October City",
    "name_ar": "مركز البحراوى للعلاج الطبيعى",
    "name_en": "Dr. Bahrawy Physiotherapy Center",
    "address_ar": "17/1/ب شارع مكتبة جامعة 6 أكتوبر - برج رويال تاورز",
    "address_en": "17/1/B 6 October University Library Street - Royal Towers",
    "phone1": "02 38383828",
    "phone2": "01111112829",
    "network": "Orange",
    "lat": 30.939194,
    "lng": 29.971043,
    "gmaps": "https://www.google.com/maps?q=30.939194,29.971043"
  },
  {
    "id": 17,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "السادس من اكتوبر",
    "city_en": "6th October City",
    "name_ar": "مركز الشريف للعلاج الطبيعى",
    "name_en": "Al Shrief Physiotherapy Center",
    "address_ar": "73المحور المركزى - ميدان الحصرى",
    "address_en": "73 Central Axis - Hosary Square",
    "phone1": "01029585990",
    "phone2": "",
    "network": "Orange",
    "lat": 30.944408,
    "lng": 29.97403,
    "gmaps": "https://www.google.com/maps?q=30.944408,29.97403"
  },
  {
    "id": 18,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "السادس من اكتوبر",
    "city_en": "6th October City",
    "name_ar": "مركز النيل التخصصى د/ صلاح عبد المنعم صوان",
    "name_en": "Al Nile Specialized Center For Physical Treatment (Dr. Salah",
    "address_ar": "سيتى مول - على الدين - الحى السابع - ميدان الحصرى",
    "address_en": "City Mall - Ali El Din - 7th District - El Hosary Square",
    "phone1": "01111120054",
    "phone2": "",
    "network": "Orange",
    "lat": 30.946575,
    "lng": 29.974052,
    "gmaps": "https://www.google.com/maps?q=30.946575,29.974052"
  },
  {
    "id": 19,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "السادس من اكتوبر",
    "city_en": "6th October City",
    "name_ar": "مركز الهلال للعلاج الطبيعى",
    "name_en": "Al Helal Physiotherapy Center",
    "address_ar": "برج رقم 1 برج الضرائب أمام البيت الرياضى - المحور المركزى ميدان الحصرى",
    "address_en": "Tower No. 1 Tax Tower in front of the Sports House - Central Axis, Hosary Square",
    "phone1": "01225725490",
    "phone2": "",
    "network": "Orange",
    "lat": 30.941715,
    "lng": 29.971006,
    "gmaps": "https://www.google.com/maps?q=30.941715,29.971006"
  },
  {
    "id": 20,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "السادس من اكتوبر",
    "city_en": "6th October City",
    "name_ar": "مركز حسبو للعلاج الطبيعى",
    "name_en": "Hasabo Center for physiotherapy",
    "address_ar": "كايرو ميديكال سنتر بالمحور المركزى",
    "address_en": "Cairo Medical Center in the central axis",
    "phone1": "01007412217",
    "phone2": "1007412218",
    "network": "Orange",
    "lat": 31.037842,
    "lng": 29.97384,
    "gmaps": "https://www.google.com/maps?q=31.037842,29.97384"
  },
  {
    "id": 21,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "السادس من اكتوبر",
    "city_en": "6th October City",
    "name_ar": "مركز طه كلينيك للعلاج الطبيعى",
    "name_en": "Taha Clinic Physiotherapy",
    "address_ar": "المحور المركزي عماره ٣٩ - الحي الاول المجاوره الأولي - أمام جامعه ٦ اكتوبر - اعلي الارنب الجائع",
    "address_en": "Central Axis, Building 39 - First District, First Neighborhood - Opposite 6th of October University - Above the Hungry Rabbit",
    "phone1": "01500556544",
    "phone2": "01031618825",
    "network": "Orange",
    "lat": 30.930677,
    "lng": 29.965878,
    "gmaps": "https://www.google.com/maps?q=30.930677,29.965878"
  },
  {
    "id": 22,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "السادس من اكتوبر",
    "city_en": "6th October City",
    "name_ar": "مركز لايف سبورت للعلاج الطبيعى",
    "name_en": "Life Sport Physiotherapy Center",
    "address_ar": "مول الياسمين - الحى الثامن - بجوار ماركت بيم",
    "address_en": "Al Yasmin Mall - 8th District - Next to BIM Market",
    "phone1": "01206002002 - 010060",
    "phone2": "010 65953333",
    "network": "Orange",
    "lat": 30.936012,
    "lng": 29.979067,
    "gmaps": "https://www.google.com/maps?q=30.936012,29.979067"
  },
  {
    "id": 23,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الشيخ زايد",
    "city_en": "Sheikh Zayed",
    "name_ar": "فيزيو كير للعلاج الطبيعى",
    "name_en": "Physio Care Center",
    "address_ar": "أركان مول - مبنى 5 - الدور الخامس - أمام كمبوند زايد 2000 - الشيخ زايد",
    "address_en": "Arkan Mall - Building 5 - Fifth Floor - In front of Zayed 2000 Compound - Sheikh Zayed",
    "phone1": "01024443117",
    "phone2": "01024443118",
    "network": "Orange",
    "lat": 31.111813,
    "lng": 30.060236,
    "gmaps": "https://www.google.com/maps?q=31.111813,30.060236"
  },
  {
    "id": 24,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الشيخ زايد",
    "city_en": "Sheikh Zayed",
    "name_ar": "فيزيو كير للعلاج الطبيعى",
    "name_en": "Physio Care Center",
    "address_ar": "إيدن مول - الحي الرابع - خلف كمبوند حدائق المهندسين - الشيخ زايد",
    "address_en": "Eden Mall - District 4 - Behind Hadayek El Mohandeseen Compound - Sheikh Zayed",
    "phone1": "01024443117",
    "phone2": "01024443118",
    "network": "Orange",
    "lat": 31.022074,
    "lng": 30.020117,
    "gmaps": "https://www.google.com/maps?q=31.022074,30.020117"
  },
  {
    "id": 25,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الشيخ زايد",
    "city_en": "Sheikh Zayed",
    "name_ar": "مركز ابو زهرة للعلاج الطبيعى",
    "name_en": "Abu Zahra Physical Therapy Center",
    "address_ar": "امتداد المحور المركزى برج توين تاورز - مبنى C -عيادة E",
    "address_en": "Extension of the central axis, Twin Towers - Building C - Clinic",
    "phone1": "02 37938008",
    "phone2": "01119229229 - 010220",
    "network": "Orange",
    "lat": 30.95796,
    "lng": 30.059633,
    "gmaps": "https://www.google.com/maps?q=30.95796,30.059633"
  },
  {
    "id": 26,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الشيخ زايد",
    "city_en": "Sheikh Zayed",
    "name_ar": "مركز البحراوى للعلاج الطبيعى",
    "name_en": "Dr. Bahrawy Physiotherapy Center",
    "address_ar": "توين تاورز - طريق المحور الرئيسى - مبنى C",
    "address_en": "Twin Towers - Main Axis Road - Building C",
    "phone1": "02 37938066",
    "phone2": "01551243124",
    "network": "Orange",
    "lat": 30.933596,
    "lng": 30.066746,
    "gmaps": "https://www.google.com/maps?q=30.933596,30.066746"
  },
  {
    "id": 27,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "العجوزة",
    "city_en": "Agouza",
    "name_ar": "مركز النيل التخصصى د/ صلاح عبد المنعم صوان",
    "name_en": "Al Nile Specialized Center For Physical Treatment (Dr. Salah",
    "address_ar": "146 ش 26 يوليو – ميدان سفنكس العجوزة",
    "address_en": "146 26th of July Street - Sphinx Square, Agouza",
    "phone1": "02 33474849 - 02 334",
    "phone2": "01224072373",
    "network": "Orange",
    "lat": 31.215324,
    "lng": 30.061241,
    "gmaps": "https://www.google.com/maps?q=31.215324,30.061241"
  },
  {
    "id": 28,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "العجوزة",
    "city_en": "Agouza",
    "name_ar": "مركز طه كلينيك للعلاج الطبيعى",
    "name_en": "Taha Clinic Physiotherapy",
    "address_ar": "4ميدان شاهين بجوار العبد ، العجوزة",
    "address_en": "4 Shaheen Square, next to Al-Abd, Agouza",
    "phone1": "01500556544",
    "phone2": "01031618825",
    "network": "Orange",
    "lat": 31.213274,
    "lng": 30.05145,
    "gmaps": "https://www.google.com/maps?q=31.213274,30.05145"
  },
  {
    "id": 29,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "المهندسين",
    "city_en": "Mohandiseen",
    "name_ar": "الفا فيت – مركز الصفا الطبى",
    "name_en": "Alfa Fit - Al-Safa Medical Tower",
    "address_ar": "برج الصفا الطبى – ميدان الحجاز – المهندسين",
    "address_en": "Al-Safa Medical Tower, Al-Hegaz Sq., Mohandeseen",
    "phone1": "02 33377993",
    "phone2": "0233377660",
    "network": "Orange",
    "lat": 31.197569,
    "lng": 30.05184,
    "gmaps": "https://www.google.com/maps?q=31.197569,30.05184"
  },
  {
    "id": 30,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "المهندسين",
    "city_en": "Mohandiseen",
    "name_ar": "المركز الدولى للعلاج الطبيعى وعلاج الالام",
    "name_en": "International Physical Therapy Center & Pain Management",
    "address_ar": "3ش شهاب متفرع من شارع جامعة الدول العربيه - المهندسين",
    "address_en": "3 Shehab St., of Gamet El Dwel El Arabia St., Mohandseen",
    "phone1": "02 37611144",
    "phone2": "012 01111211",
    "network": "Orange",
    "lat": 31.216244,
    "lng": 30.058641,
    "gmaps": "https://www.google.com/maps?q=31.216244,30.058641"
  },
  {
    "id": 31,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "المهندسين",
    "city_en": "Mohandiseen",
    "name_ar": "المركز الطبى للعلاج الطبيعى د. على حسن توفيق",
    "name_en": "Medical Center For Physiotherapy",
    "address_ar": "153 شارع السودان",
    "address_en": "153 Al Sodan St,",
    "phone1": "02 3374833",
    "phone2": "",
    "network": "Orange",
    "lat": 31.192331,
    "lng": 30.055403,
    "gmaps": "https://www.google.com/maps?q=31.192331,30.055403"
  },
  {
    "id": 32,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "المهندسين",
    "city_en": "Mohandiseen",
    "name_ar": "المركز المصرى للعلاج الطبيعى",
    "name_en": "Egyptian Center For Physiotherapy",
    "address_ar": "3 شارع السودان بجوار مترو البحوث (داخل مستشفى المروة)",
    "address_en": "3 Sudan Street, next to the research metro (inside Al-Marwa",
    "phone1": "01204547747",
    "phone2": "",
    "network": "Orange",
    "lat": 31.2037,
    "lng": 30.053211,
    "gmaps": "https://www.google.com/maps?q=31.2037,30.053211"
  },
  {
    "id": 33,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "المهندسين",
    "city_en": "Mohandiseen",
    "name_ar": "فيزيو كير للعلاج الطبيعى",
    "name_en": "Physio Care Center",
    "address_ar": "المهندسين 25 ش عبد المنعم رياض متفرع من البطل أحمد عبد العزيز",
    "address_en": "Engineers, 25 Abdel Moneim Riad Street, branching off from El Batal Ahmed Abdel Aziz Street",
    "phone1": "01024443117",
    "phone2": "01024443118",
    "network": "Orange",
    "lat": 31.225674,
    "lng": 30.049929,
    "gmaps": "https://www.google.com/maps?q=31.225674,30.049929"
  },
  {
    "id": 34,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "المهندسين",
    "city_en": "Mohandiseen",
    "name_ar": "مركز ابو زهرة للعلاج الطبيعى",
    "name_en": "Abu Zahra Physical Therapy Center",
    "address_ar": "15 ش أحمد عرابى - أعلى صيدلية نورماندى",
    "address_en": "15 Ahmed Orabi St., above Normandy Phramcay ,",
    "phone1": "02 33044499",
    "phone2": "",
    "network": "Orange",
    "lat": 31.534763,
    "lng": 30.050148,
    "gmaps": "https://www.google.com/maps?q=31.534763,30.050148"
  },
  {
    "id": 35,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "المهندسين",
    "city_en": "Mohandiseen",
    "name_ar": "مركز د.اسماعيل الخشاب",
    "name_en": "Dr.EsmaiAl Al Khashab Center",
    "address_ar": "33 شارع احمد عرابى - عمارة الشبراوى - امام عمر افندى",
    "address_en": "33 Ahmed Orabi St, Al Shabrawi Bulding, Infront Of Omar",
    "phone1": "02 33046333",
    "phone2": "01112513032",
    "network": "Orange",
    "lat": 31.20498,
    "lng": 30.063988,
    "gmaps": "https://www.google.com/maps?q=31.20498,30.063988"
  },
  {
    "id": 36,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "المهندسين",
    "city_en": "Mohandiseen",
    "name_ar": "مركز لايف سبورت للعلاج الطبيعى",
    "name_en": "Life Sport Physiotherapy Center",
    "address_ar": "253شارع السودان - ميدان لبنان - بجوار قسم العجوزة الجديد",
    "address_en": "253 Sudan Street - Lebanon Square - Next to the new Agouza Police Station",
    "phone1": "01206002002 - 010060",
    "phone2": "010 65953333",
    "network": "Orange",
    "lat": 31.189804,
    "lng": 30.06161,
    "gmaps": "https://www.google.com/maps?q=31.189804,30.06161"
  },
  {
    "id": 37,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الهرم",
    "city_en": "Haram",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "١١٤ برج جوميرا - ش الهرم الرئيسي - محطة سهل حمزة - اعلى البنك الاهلي - بجوار رنين - الدور الأول علوي - شقة ١",
    "address_en": "114 Jumeirah Tower - Al-Haram Main Street - Sahl Hamza Station - Above the National Bank - Next to Raneen - First Floor - Apartment 1",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 29.992195,
    "lng": 31.155416,
    "gmaps": "https://www.google.com/maps?q=29.992195,31.155416"
  },
  {
    "id": 38,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الهرم",
    "city_en": "Haram",
    "name_ar": "مركز النيل التخصصى د/ صلاح عبد المنعم صوان",
    "name_en": "Al Nile Specialized Center For Physical Treatment (Dr. Salah",
    "address_ar": "146شارع الهرم - سباتس - أمام بنك التعمير والأسكان",
    "address_en": "146 Al Haram Street - Spatz - in front of the Housing and Development Bank",
    "phone1": "01111120054",
    "phone2": "",
    "network": "Orange",
    "lat": 31.172443,
    "lng": 29.998606,
    "gmaps": "https://www.google.com/maps?q=31.172443,29.998606"
  },
  {
    "id": 39,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الهرم",
    "city_en": "Haram",
    "name_ar": "مركز الهلال للعلاج الطبيعى",
    "name_en": "Al Helal Physiotherapy Center",
    "address_ar": "11 شارع فؤاد الدمرداش - اول يمين من شارع الثلاثينى - العمرانية الغربية",
    "address_en": "11 Foaad St, from Al Thalatheny St",
    "phone1": "010 10084814",
    "phone2": "",
    "network": "Orange",
    "lat": 31.20251,
    "lng": 29.999348,
    "gmaps": "https://www.google.com/maps?q=31.20251,29.999348"
  },
  {
    "id": 40,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الهرم",
    "city_en": "Haram",
    "name_ar": "مركز حسبو للعلاج الطبيعى",
    "name_en": "Hasabo Center for physiotherapy",
    "address_ar": "7 - أ - عمارات بنك التعمير والاسكان - الهرم - القاهره - مصر",
    "address_en": "7 A Bank El Tameer we el Eskan buildings , Haram",
    "phone1": "02-37720840",
    "phone2": "",
    "network": "Orange",
    "lat": 31.15869,
    "lng": 29.992813,
    "gmaps": "https://www.google.com/maps?q=31.15869,29.992813"
  },
  {
    "id": 41,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الهرم",
    "city_en": "Haram",
    "name_ar": "مركز د.اسماعيل الخشاب",
    "name_en": "Dr.EsmaiAl Al Khashab Center",
    "address_ar": "410 شارع الهرم - اعلى بنك بلوم - نصر الدين",
    "address_en": "410 Al Haram St, Above Bloom Bank, Nasr El Deen",
    "phone1": "02 35702431-02 35704",
    "phone2": "01000058781",
    "network": "Orange",
    "lat": 31.323568,
    "lng": 29.9819,
    "gmaps": "https://www.google.com/maps?q=31.323568,29.9819"
  },
  {
    "id": 42,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "الهرم",
    "city_en": "Haram",
    "name_ar": "مركز لايف سبورت للعلاج الطبيعى",
    "name_en": "Life Sport Physiotherapy Center",
    "address_ar": "اشارع أشرف البطران - الليبينى هرم - بجوار نفق الهرم",
    "address_en": "Ashraf Al-Batran Street - Al-Libyani Pyramids - next to the Pyramids Tunnel",
    "phone1": "01206002002 - 010060",
    "phone2": "010 65953333",
    "network": "Orange",
    "lat": 31.14976,
    "lng": 29.98673,
    "gmaps": "https://www.google.com/maps?q=31.14976,29.98673"
  },
  {
    "id": 43,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "امبابة",
    "city_en": "Embaba",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "58  ش نادي إمبابة الرياضي - أمام اسماك جمبريكا - أعلى كافتيريا دياسطي",
    "address_en": "58 Imbaba Sports Club Street - Opposite Gambreka Fish",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.08489,
    "lng": 31.218767,
    "gmaps": "https://www.google.com/maps?q=30.08489,31.218767"
  },
  {
    "id": 44,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "حدائق الاهرام",
    "city_en": "Hadayek Al Ahram",
    "name_ar": "مركز فال للعلاج الطبيعى",
    "name_en": "Fal Physiotherapy Center",
    "address_ar": "135ج حدائق الأهرام– ش 3",
    "address_en": "135 G Hadayek El Ahram , street # 3",
    "phone1": "02 33907759",
    "phone2": "02 33907760",
    "network": "Orange",
    "lat": 31.0993,
    "lng": 29.951979,
    "gmaps": "https://www.google.com/maps?q=31.0993,29.951979"
  },
  {
    "id": 45,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "صفط اللبن",
    "city_en": "Saft Al Laban",
    "name_ar": "مركز الهلال للعلاج الطبيعى",
    "name_en": "Al Helal Physiotherapy Center",
    "address_ar": "2 شارع محمود الفيومى - خلف سنترال صفط اللبن",
    "address_en": "2 Mahmoud Al Fayoumy St,",
    "phone1": "010 10084894",
    "phone2": "",
    "network": "Orange",
    "lat": 31.17143,
    "lng": 30.024597,
    "gmaps": "https://www.google.com/maps?q=31.17143,30.024597"
  },
  {
    "id": 46,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "فيصل",
    "city_en": "Faisal",
    "name_ar": "مركز الهلال للعلاج الطبيعى",
    "name_en": "Al Helal Physiotherapy Center",
    "address_ar": "195 شارع الملك فيصل - الكوم الاخضر - أعلى معامل الفا",
    "address_en": "95 Al Malek Faisal - Al Kom Al Akhdar - Above Alfa Lab",
    "phone1": "01121122121",
    "phone2": "010 30603332",
    "network": "Orange",
    "lat": 31.238628,
    "lng": 30.038462,
    "gmaps": "https://www.google.com/maps?q=31.238628,30.038462"
  },
  {
    "id": 47,
    "governorate_ar": "الجيزة",
    "governorate_en": "Giza",
    "city_ar": "فيصل",
    "city_en": "Faisal",
    "name_ar": "مركز طه كلينيك للعلاج الطبيعى",
    "name_en": "Taha Clinic Physiotherapy",
    "address_ar": "المطبعه فيصل برج بانوراما بلازا الدور الخامس اعلي صيدلية دلمار و عطاالله",
    "address_en": "Faisal Printing Press, Panorama Plaza Tower, 5th Floor, above Delmar Pharmacy and Attallah Pharmacy",
    "phone1": "01500556544",
    "phone2": "01031618825",
    "network": "Orange",
    "lat": 31.166744,
    "lng": 30.000729,
    "gmaps": "https://www.google.com/maps?q=31.166744,30.000729"
  },
  {
    "id": 48,
    "governorate_ar": "الدقهلية",
    "governorate_en": "Dakhlia",
    "city_ar": "الدقهلية",
    "city_en": "Dakhlia",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "ش الجمهورية - برج السوسن بلازا - ناصية محمد فتحي",
    "address_en": "El Gomhoria Street – Soussan Plaza Tower – Corner of Mohamed Fathy Street",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 31.045694,
    "lng": 31.37125,
    "gmaps": "https://www.google.com/maps?q=31.045694,31.37125"
  },
  {
    "id": 49,
    "governorate_ar": "الدقهلية",
    "governorate_en": "Dakhlia",
    "city_ar": "الدقهلية",
    "city_en": "Dakhlia",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "ش قناة السويس - برج المدينة المنورة - اعلى غبور اوتو - بجوار هايبر ميلانو - دور ٢",
    "address_en": "Suez Canal Street – Al Madina Al Monawara Tower – Above Ghabbour Auto – Next to Hyper Milano – 2nd Floor",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 31.050638,
    "lng": 31.39936,
    "gmaps": "https://www.google.com/maps?q=31.050638,31.39936"
  },
  {
    "id": 50,
    "governorate_ar": "السويس",
    "governorate_en": "Suez",
    "city_ar": "السويس",
    "city_en": "Suez",
    "name_ar": "المركز المصرى للعلاج الطبيعى",
    "name_en": "Egyptian Center For Physiotherapy",
    "address_ar": "برج الدوشى أمام بنك الأسكندرية - الأربعين (داخل مستشفى القنال)",
    "address_en": "El Doshy Tower in front of Alex Bank - El Arbaeen (Inside Canal Hospital)",
    "phone1": "01204547747",
    "phone2": "",
    "network": "Orange",
    "lat": 29.977869,
    "lng": 32.544464,
    "gmaps": "https://www.google.com/maps?q=32.544464,29.977869"
  },
  {
    "id": 51,
    "governorate_ar": "السويس",
    "governorate_en": "Suez",
    "city_ar": "السويس",
    "city_en": "Suez",
    "name_ar": "المركز المصرى للعلاج الطبيعى",
    "name_en": "Egyptian Center For Physiotherapy",
    "address_ar": "517 شارع الجيش - برج البطل",
    "address_en": "517 Army Street - Al Batal Tower",
    "phone1": "01092330766",
    "phone2": "01204547747",
    "network": "Orange",
    "lat": 29.977873,
    "lng": 32.54704,
    "gmaps": "https://www.google.com/maps?q=32.54704,29.977873"
  },
  {
    "id": 52,
    "governorate_ar": "السويس",
    "governorate_en": "Suez",
    "city_ar": "السويس",
    "city_en": "Suez",
    "name_ar": "مركز الصفوة للعلاج الطبيعى",
    "name_en": "Al Safwa Physiotherapy Center - Suez",
    "address_ar": "شارع الجيش - برج البارون",
    "address_en": "Army Street - Baron Tower",
    "phone1": "01030900134",
    "phone2": "",
    "network": "Orange",
    "lat": 29.991875,
    "lng": 32.51491,
    "gmaps": "https://www.google.com/maps?q=32.51491,29.991875"
  },
  {
    "id": 53,
    "governorate_ar": "السويس",
    "governorate_en": "Suez",
    "city_ar": "السويس",
    "city_en": "Suez",
    "name_ar": "مركز الصفوة للعلاج الطبيعى",
    "name_en": "Al Safwa Physiotherapy Center - Suez",
    "address_ar": "مول دريم - السلام2",
    "address_en": "Dream Mall - Al Salam 2",
    "phone1": "01020201295",
    "phone2": "",
    "network": "Orange",
    "lat": 29.991798,
    "lng": 32.49696,
    "gmaps": "https://www.google.com/maps?q=32.49696,29.991798"
  },
  {
    "id": 54,
    "governorate_ar": "السويس",
    "governorate_en": "Suez",
    "city_ar": "السويس",
    "city_en": "Suez",
    "name_ar": "مركز الصفوة للعلاج الطبيعى",
    "name_en": "Al Safwa Physiotherapy Center - Suez",
    "address_ar": "شارع الجيش - برج عباد الرحمن - الأربعين",
    "address_en": "Army Street - Abbad Al Rahman Tower - Al Arbaeen",
    "phone1": "01018394980",
    "phone2": "",
    "network": "Orange",
    "lat": 29.977589,
    "lng": 32.544983,
    "gmaps": "https://www.google.com/maps?q=32.544983,29.977589"
  },
  {
    "id": 55,
    "governorate_ar": "الشرقية",
    "governorate_en": "Sharkeya",
    "city_ar": "ابو حماد",
    "city_en": "Abo Hammad",
    "name_ar": "مركز يحيى للعلاج الطبيعى",
    "name_en": "Yehia Physiotherapy Center",
    "address_ar": "شارع بور سعيد - بجوار مشغل ابو عزب",
    "address_en": "Port Saied St,",
    "phone1": "055 3416688",
    "phone2": "",
    "network": "Orange",
    "lat": 31.717094,
    "lng": 30.609476,
    "gmaps": "https://www.google.com/maps?q=31.717094,30.609476"
  },
  {
    "id": 56,
    "governorate_ar": "الشرقية",
    "governorate_en": "Sharkeya",
    "city_ar": "الزقازيق",
    "city_en": "Zagazig",
    "name_ar": "مركز الهدى للعلاج الطبيعى",
    "name_en": "Al Hoda Physiotherapy Center",
    "address_ar": "الزقازيق مفارق المنصورة امام مطعم رزق",
    "address_en": "Zagazig, Mansoura Junction, in front of Razk Restaurant",
    "phone1": "01010218349",
    "phone2": "0552367837",
    "network": "Orange",
    "lat": 31.49912,
    "lng": 30.594723,
    "gmaps": "https://www.google.com/maps?q=31.49912,30.594723"
  },
  {
    "id": 57,
    "governorate_ar": "الشرقية",
    "governorate_en": "Sharkeya",
    "city_ar": "الزقازيق",
    "city_en": "Zagazig",
    "name_ar": "مركز الهدى للعلاج الطبيعى",
    "name_en": "Al Hoda Physiotherapy Center",
    "address_ar": "الزقازيق قسم الصيادين -القناطر التسعة-بجوار فسيخ ابو طعيمة د/اسامة عادل",
    "address_en": "Zagazig, El Sayadeen Police Department - El Qanater El Tesaa - next to Abu Toeima Fesikh, Dr. Osama Adel",
    "phone1": "01015004122",
    "phone2": "0552381126",
    "network": "Orange",
    "lat": 31.49663,
    "lng": 30.594593,
    "gmaps": "https://www.google.com/maps?q=31.49663,30.594593"
  },
  {
    "id": 58,
    "governorate_ar": "الشرقية",
    "governorate_en": "Sharkeya",
    "city_ar": "الزقازيق",
    "city_en": "Zagazig",
    "name_ar": "مركز الهدى للعلاج الطبيعى",
    "name_en": "Al Hoda Physiotherapy Center",
    "address_ar": "شارع المرور - امام مدينة المسك للعطور",
    "address_en": "El Morour Street - in front of El Misk Perfumes City",
    "phone1": "01558383845",
    "phone2": "",
    "network": "Orange",
    "lat": null,
    "lng": null,
    "gmaps": ""
  },
  {
    "id": 59,
    "governorate_ar": "الشرقية",
    "governorate_en": "Sharkeya",
    "city_ar": "الشرقية",
    "city_en": "Sharkeya",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "مول الدوحة – عمارة أ – الدور الثالث – مدخل أورانج – قبل موقف الأردنية",
    "address_en": "Doha Mall – Building A – 3rd Floor – Orange Entrance – Before the Jordanian Bus Stop",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.288311,
    "lng": 31.74675,
    "gmaps": "https://www.google.com/maps?q=30.288311,31.74675"
  },
  {
    "id": 60,
    "governorate_ar": "الشرقية",
    "governorate_en": "Sharkeya",
    "city_ar": "الشرقية",
    "city_en": "Sharkeya",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "ش المحافظة - امام النساجون الشرقيون (بنزايون سابقا) - بعد سنتر شاهين - برج زادة - الدور الرابع - يمين الاسانسير.",
    "address_en": "Al Mohafaza Street – In front of Oriental Weavers (formerly Benzion) – After Shaheen Center – Zada Tower – 4th Floor – Right of the elevator",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.59064,
    "lng": 31.500334,
    "gmaps": "https://www.google.com/maps?q=30.59064,31.500334"
  },
  {
    "id": 61,
    "governorate_ar": "الشرقية",
    "governorate_en": "Sharkeya",
    "city_ar": "العاشر من رمضان",
    "city_en": "10th of Ramadan",
    "name_ar": "د.طارق عفيفى",
    "name_en": "Dr.Tarek Afifi",
    "address_ar": "المركز الطبى - بجوار قسم اول العاشر",
    "address_en": "The Medical Center - Beside 10th Of Ramadan Police Station",
    "phone1": "055 4387142",
    "phone2": "01021047565 - 010135",
    "network": "Orange",
    "lat": 31.74274,
    "lng": 30.285225,
    "gmaps": "https://www.google.com/maps?q=31.74274,30.285225"
  },
  {
    "id": 62,
    "governorate_ar": "الشرقية",
    "governorate_en": "Sharkeya",
    "city_ar": "العاشر من رمضان",
    "city_en": "10th of Ramadan",
    "name_ar": "مركز الهدى للعلاج الطبيعى",
    "name_en": "Al Hoda Physiotherapy Center",
    "address_ar": "منطقه الاردنيه - مول سينكو ٢٠٠٠ - أعلى تكنوسكان للاشعه خلف مكتبه الأسكندريه",
    "address_en": "El Ordonia Area - Cinco 2000 Mall - above Technoscan Radiology, behind Alexandria Library",
    "phone1": "01066088070",
    "phone2": "0554366622",
    "network": "Orange",
    "lat": 31.74889,
    "lng": 30.28824,
    "gmaps": "https://www.google.com/maps?q=31.74889,30.28824"
  },
  {
    "id": 63,
    "governorate_ar": "الشرقية",
    "governorate_en": "Sharkeya",
    "city_ar": "بلبيس",
    "city_en": "Belbeis",
    "name_ar": "د.طارق عفيفى",
    "name_en": "Dr.Tarek Afifi",
    "address_ar": "32 شارع أبو بكر الصديق (الطحن) بجوار مستشفى التوحيد",
    "address_en": "32 Abu Bakr Al-Siddiq Street (Al-Tahn) next to Al-Tawheed",
    "phone1": "055 2867823",
    "phone2": "01021047565 - 010135",
    "network": "Orange",
    "lat": 31.564388,
    "lng": 30.421679,
    "gmaps": "https://www.google.com/maps?q=31.564388,30.421679"
  },
  {
    "id": 64,
    "governorate_ar": "الشرقية",
    "governorate_en": "Sharkeya",
    "city_ar": "منيا القمح",
    "city_en": "Minya Al Qamh",
    "name_ar": "مركز الهدى للعلاج الطبيعى",
    "name_en": "Al Hoda Physiotherapy Center",
    "address_ar": "شارع سعد زغلول بالقرب من مستشفى سلامات د/محمد زهران",
    "address_en": "Saad Zaghloul Street, near Salamat Hospital, Dr. Mohamed Zahran",
    "phone1": "01060709998",
    "phone2": "01143581852",
    "network": "Orange",
    "lat": 31.34228,
    "lng": 30.50974,
    "gmaps": "https://www.google.com/maps?q=31.34228,30.50974"
  },
  {
    "id": 65,
    "governorate_ar": "الشرقية",
    "governorate_en": "Sharkeya",
    "city_ar": "منيا القمح",
    "city_en": "Minya Al Qamh",
    "name_ar": "مركز الهدى للعلاج الطبيعى",
    "name_en": "Al Hoda Physiotherapy Center",
    "address_ar": "بندف شارع المعهد الدينى",
    "address_en": "Bandaf, Religious Institute Street",
    "phone1": "01065425339",
    "phone2": "0553371717",
    "network": "Orange",
    "lat": 31.45773,
    "lng": 30.61814,
    "gmaps": "https://www.google.com/maps?q=31.45773,30.61814"
  },
  {
    "id": 66,
    "governorate_ar": "الغربية",
    "governorate_en": "Gharbia",
    "city_ar": "الغربية",
    "city_en": "Gharbia",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "ش د. نجاتي متفرع من شارع البحر أمام معهد الاورام - أعلى مركز سما سكان للأشعه - الدور العاشر",
    "address_en": "Dr. Nagaty Street, off El Bahr Street, in front of the Oncology Institute – Above Sama Scan Radiology Center – 10th Floor",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.80239,
    "lng": 30.99625,
    "gmaps": "https://www.google.com/maps?q=30.80239,30.99625"
  },
  {
    "id": 67,
    "governorate_ar": "الغربية",
    "governorate_en": "Gharbia",
    "city_ar": "طنطا",
    "city_en": "Tanta",
    "name_ar": "ا.د/ على عيد الديب",
    "name_en": "Dr. Ali Eid El-Deeb",
    "address_ar": "14 شارع المديرية – عمارة الدلتا للتأمين",
    "address_en": "14 El-Modereya St., El Detla insurance building",
    "phone1": "0403344444",
    "phone2": "",
    "network": "Orange",
    "lat": 30.99675,
    "lng": 30.785414,
    "gmaps": "https://www.google.com/maps?q=30.99675,30.785414"
  },
  {
    "id": 68,
    "governorate_ar": "الفيوم",
    "governorate_en": "Fayoum",
    "city_ar": "الفيوم",
    "city_en": "Fayoum",
    "name_ar": "مركز رعاية للعلاج الطبيعى",
    "name_en": "Reaya Physiotherapy Center",
    "address_ar": "شارع أحمد شوقى أمام فيلا المحافظ - برج الخضر - الفيوم",
    "address_en": "Ahmed Shawky Street in front of the Governor's Villa - Al-Khidr Tower - Fayoum",
    "phone1": "01000067086",
    "phone2": "",
    "network": "Orange",
    "lat": 30.841658,
    "lng": 29.321297,
    "gmaps": "https://www.google.com/maps?q=30.841658,29.321297"
  },
  {
    "id": 69,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "التجمع الاول",
    "city_en": "1st Settlement",
    "name_ar": "مركز كان للعلاج الطبيعى",
    "name_en": "Can Physiotherapy Center",
    "address_ar": "محور مصطفى كامل - أعلى مستشفى تبارك للأطفال - بجوار قبانى",
    "address_en": "Mostafa Kamel Axis - Above Tabarak Children's Hospital - Beside Qabbani",
    "phone1": "01013988996",
    "phone2": "",
    "network": "Orange",
    "lat": 31.447138,
    "lng": 30.060581,
    "gmaps": "https://www.google.com/maps?q=31.447138,30.060581"
  },
  {
    "id": 70,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "التجمع الخامس",
    "city_en": "Fifth Settlement",
    "name_ar": "الشركة الالمانية للرعاية الصحية",
    "name_en": "German Medical Healthcare Coporation",
    "address_ar": "نادى بلاتينيوم",
    "address_en": "Platinum Club",
    "phone1": "01001812181",
    "phone2": "",
    "network": "Silver",
    "lat": 31.529972,
    "lng": 30.037178,
    "gmaps": "https://www.google.com/maps?q=31.529972,30.037178"
  },
  {
    "id": 71,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "التجمع الخامس",
    "city_en": "Fifth Settlement",
    "name_ar": "فيزيو كير للعلاج الطبيعى",
    "name_en": "Physio Care Center",
    "address_ar": "ويست بارك خلف مول العرب طريق جمال عبد الناصر بجوار ماركت خير زمان",
    "address_en": "West Park, behind Mall of Arabia, Gamal Abdel Nasser Road, next to Kheir Zaman Market",
    "phone1": "01024443117",
    "phone2": "01024443118",
    "network": "Orange",
    "lat": 31.486357,
    "lng": 30.006702,
    "gmaps": "https://www.google.com/maps?q=31.486357,30.006702"
  },
  {
    "id": 72,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "التجمع الخامس",
    "city_en": "Fifth Settlement",
    "name_ar": "مركز ابو زهرة للعلاج الطبيعى",
    "name_en": "Abu Zahra Physical Therapy Center",
    "address_ar": "ميديكال بارك بريميير (2) - خلف المستشفى الجوى - شارع التسعين",
    "address_en": "Medical Park Premier (2), Behind Air Force Hospital, 90th St",
    "phone1": "02 28123567",
    "phone2": "01144004080 - 010060",
    "network": "Orange",
    "lat": 31.578558,
    "lng": 30.018856,
    "gmaps": "https://www.google.com/maps?q=31.578558,30.018856"
  },
  {
    "id": 73,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "التجمع الخامس",
    "city_en": "Fifth Settlement",
    "name_ar": "مركز طه كلينيك للعلاج الطبيعى",
    "name_en": "Taha Clinic Physiotherapy",
    "address_ar": "162 شارع التسعين الشمالي - مول cmc الدور b1 عياده 35",
    "address_en": "162 North 90th Street - CMC Mall, Floor B1, Clinic 35",
    "phone1": "01500556544",
    "phone2": "01031618825",
    "network": "Orange",
    "lat": 31.434116,
    "lng": 30.020712,
    "gmaps": "https://www.google.com/maps?q=31.434116,30.020712"
  },
  {
    "id": 74,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "التجمع الخامس",
    "city_en": "Fifth Settlement",
    "name_ar": "مركز كان للعلاج الطبيعى",
    "name_en": "Can Physiotherapy Center",
    "address_ar": "شارع التسعين - مول كور بيزنس - الحى الأول - أمام بنزينة أمارات مصر",
    "address_en": "90th Street - Core Business Mall - First District - in front of Emarat Misr Gas Station",
    "phone1": "011 11202033",
    "phone2": "",
    "network": "Orange",
    "lat": 31.429813,
    "lng": 30.009945,
    "gmaps": "https://www.google.com/maps?q=31.429813,30.009945"
  },
  {
    "id": 75,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "الشروق",
    "city_en": "Al Sherouk",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "مدينة الشروق - قطعة ٨٤ - مول ميديكال بوينت -  الشروق ٢ - بجوار فاليو مول",
    "address_en": "Al Shorouk City - Plot 84 - Medical Point Mall - Al Shorouk 2 - Next to Value Mall",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.155972,
    "lng": 31.640972,
    "gmaps": "https://www.google.com/maps?q=30.155972,31.640972"
  },
  {
    "id": 76,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "العباسية",
    "city_en": "Abbasseya",
    "name_ar": "مركز الهدى للعلاج الطبيعى",
    "name_en": "Al Hoda Physiotherapy Center",
    "address_ar": "5ش العباسية ميدان الظاهر بيبرس بجوار مترو الجيش",
    "address_en": "5 El Abbasiya Street, El Daher Baybars Square, next to El Geish Metro",
    "phone1": "01008747920",
    "phone2": "",
    "network": "Orange",
    "lat": 31.26564,
    "lng": 30.062416,
    "gmaps": "https://www.google.com/maps?q=31.26564,30.062416"
  },
  {
    "id": 77,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "العباسية",
    "city_en": "Abbasseya",
    "name_ar": "مركز الهدى للعلاج الطبيعى",
    "name_en": "Al Hoda Physiotherapy Center",
    "address_ar": "5شارع العباسية – ميدان الظاهر بيبرس – بجوار مترو الجيش - العباسية",
    "address_en": "5 Abbasia Street – Al-Zaher Baybars Square – Next to the Army Metro Station – Abbasia",
    "phone1": "01060055753",
    "phone2": "",
    "network": "Orange",
    "lat": 31.374826,
    "lng": 30.052557,
    "gmaps": "https://www.google.com/maps?q=31.374826,30.052557"
  },
  {
    "id": 78,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "القاهرة",
    "city_en": "Cairo",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "( مركز الطبيب ) 3 ش الطبيب من شارع اخناتون - خلف أون ذا ران - بالقرب من سعودى ماركت",
    "address_en": "Al-Tabeeb (3 Al-Tabeeb Street, off Akhnaton Street - behind On the Run - near Saudi Market)",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.004265,
    "lng": 31.423206,
    "gmaps": "https://www.google.com/maps?q=30.004265,31.423206"
  },
  {
    "id": 79,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "القاهرة",
    "city_en": "Cairo",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "التجمع الخامس - محور محمد نجيب - داخل مول سواي - أمام كمبوند ديار",
    "address_en": "Fifth Settlement - Mohamed Naguib Axis - Inside Sway Mall - In front of Diyar Compound",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.017445,
    "lng": 31.475735,
    "gmaps": "https://www.google.com/maps?q=30.017445,31.475735"
  },
  {
    "id": 80,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "القاهرة",
    "city_en": "Cairo",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "إيست هب - المول الطبي - الدور الثاني",
    "address_en": "East Hub - Medical Mall - Second Floor",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.084368,
    "lng": 31.678818,
    "gmaps": "https://www.google.com/maps?q=30.084368,31.678818"
  },
  {
    "id": 81,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "القاهرة",
    "city_en": "Cairo",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "31 ش زهير صبري - متفرع من شارع الطيران - خلف بنك الـــCib - وبالقرب من مسجد نورى الخطاب - الدور الارضي",
    "address_en": "31 Zuhair Sabry Street, off Al Tayaran Street, behind CIB Bank, near Nouri Al Khattab Mosque, Ground Floor",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.054777,
    "lng": 31.327555,
    "gmaps": "https://www.google.com/maps?q=30.054777,31.327555"
  },
  {
    "id": 82,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "القاهرة",
    "city_en": "Cairo",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "53 ش حسن المأمون - داخل مركز التيسير الطبي - واعلى صيدلية دكتورة مروة - الدور الاول",
    "address_en": "53 Hassan El Maamoun Street - Inside Al Taysir Medical Center - Above Dr. Marwa's Pharmacy - First Floor",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.059074,
    "lng": 31.357992,
    "gmaps": "https://www.google.com/maps?q=30.059074,31.357992"
  },
  {
    "id": 83,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "القاهرة",
    "city_en": "Cairo",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "183 ش التحرير – عمارة استراند – الدور الرابع - شقة ( 13 )",
    "address_en": "183 El Tahrir Street, Strand Building, 4th Floor, Apartment (13)",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.044195,
    "lng": 31.2425,
    "gmaps": "https://www.google.com/maps?q=30.044195,31.2425"
  },
  {
    "id": 84,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "القاهرة",
    "city_en": "Cairo",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "38 ش رمسيس تقاطع عماد الدين - بجوار مستشفى الهلال - عمارة السجل التجارى - الدور الثامن",
    "address_en": "38 Ramses Street, intersection of Emad El Din Street - next to Al Hilal Hospital - Commercial Registry Building - 8th Floor",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.059656,
    "lng": 31.244856,
    "gmaps": "https://www.google.com/maps?q=30.059656,31.244856"
  },
  {
    "id": 85,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "القاهرة",
    "city_en": "Cairo",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "آخر كوبري عرابي - برج سيتي مول مدخل 1&2 - أعلى بي تك وحلواني العبد - الدور العاشر - يمين الأسانسير",
    "address_en": "Shubra El Kheima - End of Orabi Bridge - City Mall Tower, Entrances 1 & 2 - Above B.Tech and El Abd Sweets - 10th Floor - Right of the Elevator",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.121758,
    "lng": 31.248701,
    "gmaps": "https://www.google.com/maps?q=30.121758,31.248701"
  },
  {
    "id": 86,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "القاهرة",
    "city_en": "Cairo",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "الحي المتميز شمالاً - جنوب دار مصر - ميديكال بوينت - الدور الارضي",
    "address_en": "North Distinguished Neighborhood - South of Dar Misr - Medical Point - Ground Floor",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.122086,
    "lng": 31.724892,
    "gmaps": "https://www.google.com/maps?q=30.122086,31.724892"
  },
  {
    "id": 87,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "القبة",
    "city_en": "Al Koba",
    "name_ar": "د. كامل حسين كامل",
    "name_en": "Dr. KamAl Hussein Kamel",
    "address_ar": "61 ش مصر والسودان - دير الملاك – حدائق القبة",
    "address_en": "61 Misr wa AlSudan St., Kobry Al-Quba",
    "phone1": "02 24820352",
    "phone2": "01222220384",
    "network": "Orange",
    "lat": 31.271421,
    "lng": 30.061506,
    "gmaps": "https://www.google.com/maps?q=31.271421,30.061506"
  },
  {
    "id": 88,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "القبة",
    "city_en": "Al Koba",
    "name_ar": "مركز الزايد للعلاج الطبيعى د. زايد عبد الرحيم محمد",
    "name_en": "Al Zayed Physiotheraby center - Dr. A. Rehim Zayed",
    "address_ar": "89 ش وادى النيل - أمام مستشفى وادى النيل - محطة التأمين الصحى",
    "address_en": "89 Wady El Nile St., infront of Wady El nile Hospital",
    "phone1": "02 22580238 /9",
    "phone2": "",
    "network": "Orange",
    "lat": 31.286524,
    "lng": 30.090004,
    "gmaps": "https://www.google.com/maps?q=31.286524,30.090004"
  },
  {
    "id": 89,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "المعادى",
    "city_en": "Maadi",
    "name_ar": "المركز الذهبى للعلاج الطبيعى",
    "name_en": "Golden Center for Physical Therapy",
    "address_ar": "5شارع 153 - برج الحرية - ميدان الحرية - المعادى",
    "address_en": "5 Street 153 - Freedom Tower - Freedom Square - Maadi",
    "phone1": "01018112426",
    "phone2": "",
    "network": "Orange",
    "lat": 31.110344,
    "lng": 29.889105,
    "gmaps": "https://www.google.com/maps?q=31.110344,29.889105"
  },
  {
    "id": 90,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "المعادى",
    "city_en": "Maadi",
    "name_ar": "د.طارق عفيفى",
    "name_en": "Dr.Tarek Afifi",
    "address_ar": "1/1 شارع فلسطين - بجوار البندر مول - المعادى الجديدة",
    "address_en": "1/1 Palestine Street - Beside Bandar Mall",
    "phone1": "02 25175195",
    "phone2": "01021047565 - 010135",
    "network": "Orange",
    "lat": 31.260864,
    "lng": 29.957102,
    "gmaps": "https://www.google.com/maps?q=31.260864,29.957102"
  },
  {
    "id": 91,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "المعادى",
    "city_en": "Maadi",
    "name_ar": "فيزيو كير للعلاج الطبيعى",
    "name_en": "Physio Care Center",
    "address_ar": "عماره 5 شارع وادي النيل بجوار شركه الكهرباء",
    "address_en": "Building 5, Wadi El Nil Street, next to the electricity company",
    "phone1": "01024443117",
    "phone2": "01024443118",
    "network": "Orange",
    "lat": 31.290133,
    "lng": 29.960697,
    "gmaps": "https://www.google.com/maps?q=31.290133,29.960697"
  },
  {
    "id": 92,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "المعادى",
    "city_en": "Maadi",
    "name_ar": "مركز اما للعلاج الطبيعى",
    "name_en": "EMA Physiotherapy Center",
    "address_ar": "10 شارع 287 - متفرع من شارع الجزائر",
    "address_en": "10 Street No 287 From Al Gazayer St, New Maadi",
    "phone1": "02 25190600",
    "phone2": "",
    "network": "Orange",
    "lat": 31.276934,
    "lng": 29.977093,
    "gmaps": "https://www.google.com/maps?q=31.276934,29.977093"
  },
  {
    "id": 93,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "المعادى",
    "city_en": "Maadi",
    "name_ar": "مركز د.اسماعيل الخشاب",
    "name_en": "Dr.EsmaiAl Al Khashab Center",
    "address_ar": "زهراء المعادى - عمارة 3 - بلوك 76 - الشطر العاشر - امام كارفور",
    "address_en": "Zahraa Al Maadi",
    "phone1": "02 29704464",
    "phone2": "011112263344",
    "network": "Orange",
    "lat": 31.323568,
    "lng": 29.9819,
    "gmaps": "https://www.google.com/maps?q=31.323568,29.9819"
  },
  {
    "id": 94,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "المعادى",
    "city_en": "Maadi",
    "name_ar": "مركز طه كلينيك للعلاج الطبيعى",
    "name_en": "Taha Clinic Physiotherapy",
    "address_ar": "29شارع النصر الدور الثالث امام سيراميكا كليوباترا",
    "address_en": "29 El Nasr Street, 3rd Floor, in front of Ceramica Cleopatra",
    "phone1": "01500556544",
    "phone2": "01031618825",
    "network": "Orange",
    "lat": 31.279411,
    "lng": 29.974783,
    "gmaps": "https://www.google.com/maps?q=31.279411,29.974783"
  },
  {
    "id": 95,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "المعادى",
    "city_en": "Maadi",
    "name_ar": "مركز كان للعلاج الطبيعى",
    "name_en": "Can Physiotherapy Center",
    "address_ar": "عمارات بيتشو - عمارة 6 - المرحلة الثانية - أمام مرور المعادى",
    "address_en": "Bichu Buildings - Building 6 - Phase Two - in front of Maadi Traffic",
    "phone1": "01110960988",
    "phone2": "",
    "network": "Orange",
    "lat": 31.620878,
    "lng": 29.969904,
    "gmaps": "https://www.google.com/maps?q=31.620878,29.969904"
  },
  {
    "id": 96,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "المقطم",
    "city_en": "Mokatam",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "33 ش 9 المقطم - بجوار مستشفى دار الأم - أمام فرع اتصالات - بعد عمارتين من  رنين و النساجون الشرقيون",
    "address_en": "33 Street 9, Mokattam - Next to Dar Al-Om Hospital - Opposite Etisalat Branch - Two buildings past Raneen",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.013721,
    "lng": 31.285917,
    "gmaps": "https://www.google.com/maps?q=30.013721,31.285917"
  },
  {
    "id": 97,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "المقطم",
    "city_en": "Mokatam",
    "name_ar": "مركز الجولف للعلاج الطبيعى",
    "name_en": "Golf Physiotherapy Center",
    "address_ar": "مجمع عيادات شارع 9 أمام مسجد القدس شارع القدس بجوار بنزينة موبيل",
    "address_en": "Clinics Complex, Street 9, in front of Al-Quds Mosque, Al-Quds Street, next to Mobil Gas Station",
    "phone1": "02 28462600",
    "phone2": "012 22290123",
    "network": "Orange",
    "lat": 31.303005,
    "lng": 30.011549,
    "gmaps": "https://www.google.com/maps?q=31.303005,30.011549"
  },
  {
    "id": 98,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "المنيل",
    "city_en": "Manial",
    "name_ar": "مركز البرج للعلاج الطبيعى",
    "name_en": "Al borg physiotherapy",
    "address_ar": "أول شارع محمد فريد أمام مستشفى الندى - المنيل",
    "address_en": "Beginning of Mohamed Farid Street in front of Al Nada Hospital - Manial",
    "phone1": "02 23635509",
    "phone2": "010 05504412",
    "network": "Orange",
    "lat": 31.225983,
    "lng": 30.01848,
    "gmaps": "https://www.google.com/maps?q=31.225983,30.01848"
  },
  {
    "id": 99,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "جسر السويس",
    "city_en": "Gesr A lSuez",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "76 أ - برج الخليل - جسر السويس الرئيسي - ميدان الألف مسكن - أمام مطعم كرم الشام مباشرة - وبجوار تاون تيم مباشرة - الدور الثاني علوى - شقة 4",
    "address_en": "76A - El Khalil Tower - Gesr El Suez Main Road - Alf Maskan Square - Directly opposite Karam El Sham Restaurant - Next to Town Team - Second Floor - Apartment 4",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.119858,
    "lng": 31.34132,
    "gmaps": "https://www.google.com/maps?q=30.119858,31.34132"
  },
  {
    "id": 100,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "حلوان",
    "city_en": "Helwan",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "حلوان - 44 ش منصور تقاطع شارع المراغي - برج الصيفي (2) - بجانب مترو حلوان - اعلى حلواني العيسوي \n الدور الخامس - يمين الاسانسير - شقة رقم (5)",
    "address_en": "44 Mansour Street, intersection of El Maraghi Street - El Seify Tower (2) - next to Helwan Metro Station - above El Eisawy Sweets\nFifth Floor - right of the elevator - Apartment No. (5)",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 29.848814,
    "lng": 31.335146,
    "gmaps": "https://www.google.com/maps?q=29.848814,31.335146"
  },
  {
    "id": 101,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "حلوان",
    "city_en": "Helwan",
    "name_ar": "مركز طه كلينيك للعلاج الطبيعى",
    "name_en": "Taha Clinic Physiotherapy",
    "address_ar": "عماره رقم ١/أ الدور الاول شارع محمد سيد احمد امام مدرسه ألياس - اعلي اورانج وتري بون",
    "address_en": "Building No. 1/A, First Floor, Mohamed Sayed Ahmed Street, in front of Elias School - above Orange and Treebone",
    "phone1": "01500556544",
    "phone2": "01031618825",
    "network": "Orange",
    "lat": null,
    "lng": null,
    "gmaps": ""
  },
  {
    "id": 102,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "شبرا",
    "city_en": "Shobra",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "٢٣٨ ش شبرا  - الخلفاوى - أعلى المصرف المتحد - الدور الثالث",
    "address_en": "238 Shubra Street - El-Khalafawy - Above United Bank - Third Floor",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.096067,
    "lng": 31.245132,
    "gmaps": "https://www.google.com/maps?q=30.096067,31.245132"
  },
  {
    "id": 103,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "شبرا",
    "city_en": "Shobra",
    "name_ar": "المركز التخصصى للعلاج الطبيعى و انقاص الوزن د. سرحان فهمى",
    "name_en": "Dr. Sarhan Fahmy",
    "address_ar": "53 ش شبرا – برج السعد – الدور الرابع – شقة 402",
    "address_en": "53 Shoubra St. – El Saad Tower – 4th Floor – flat # 402",
    "phone1": "0225769408",
    "phone2": "",
    "network": "Orange",
    "lat": 31.263119,
    "lng": 30.08952,
    "gmaps": "https://www.google.com/maps?q=31.263119,30.08952"
  },
  {
    "id": 104,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "شبرا",
    "city_en": "Shobra",
    "name_ar": "مركز الشروق للعلاج الطبيعى - د/ماجد عبد المقصود",
    "name_en": "Al Shorouk Physiotherapy Center",
    "address_ar": "5 شارع دنشواى - امام مستشفى الساحل التعليمى -بجوار اولاد رجب",
    "address_en": "5 Denshway St,",
    "phone1": "02 22007005",
    "phone2": "",
    "network": "Orange",
    "lat": 31.18264,
    "lng": 30.008429,
    "gmaps": "https://www.google.com/maps?q=31.18264,30.008429"
  },
  {
    "id": 105,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "شبرا",
    "city_en": "Shobra",
    "name_ar": "مركز طه كلينيك للعلاج الطبيعى",
    "name_en": "Taha Clinic Physiotherapy",
    "address_ar": "68شارع شبرا ( طوسون) بعد حلواني لابوار اعلي سالي للاحذية - شبرا",
    "address_en": "68 Shubra Street (Tuson), after Labwar Sweets, above Sally Shoes - Shubra",
    "phone1": "01500556544",
    "phone2": "01031618825",
    "network": "Orange",
    "lat": 31.244974,
    "lng": 30.075573,
    "gmaps": "https://www.google.com/maps?q=31.244974,30.075573"
  },
  {
    "id": 106,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مدينة نصر",
    "city_en": "Nasr City",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "14 ش عطية الصوالحى – متفرع من مكرم عبيد – أمام السراج مول - الدور الثالث",
    "address_en": "14 Atiya El Sawalhy Street, off Makram Ebeid Street, in front of El Serag Mall, 3rd Floor",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.051472,
    "lng": 31.348167,
    "gmaps": "https://www.google.com/maps?q=30.051472,31.348167"
  },
  {
    "id": 107,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مدينة نصر",
    "city_en": "Nasr City",
    "name_ar": "فيزيو كير للعلاج الطبيعى",
    "name_en": "Physio Care Center",
    "address_ar": "شارع المخيم الدائم – مدينة نصر – امتداد الوفاء والأمل – بجوار Go Bus",
    "address_en": "Permanent Camp Street – Nasr City – Extension of Al Wafaa Wal Amal – Next to Go Bus",
    "phone1": "01024443117",
    "phone2": "01024443118",
    "network": "Orange",
    "lat": 31.486357,
    "lng": 30.006702,
    "gmaps": "https://www.google.com/maps?q=31.486357,30.006702"
  },
  {
    "id": 108,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مدينة نصر",
    "city_en": "Nasr City",
    "name_ar": "مركز البرج للعلاج الطبيعى",
    "name_en": "Al borg physiotherapy",
    "address_ar": "15شارع النصر عمارات النصر ميدان رابعة العدوية أمام مسجد رابعة - مدينة نصر",
    "address_en": "15 Al-Nasr Street, Al-Nasr Buildings, Rabaa Al-Adawiya Square, in front of Rabaa Mosque - Nasr City",
    "phone1": "02 226717160",
    "phone2": "010 33356840",
    "network": "Orange",
    "lat": 31.324272,
    "lng": 30.067883,
    "gmaps": "https://www.google.com/maps?q=31.324272,30.067883"
  },
  {
    "id": 109,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مدينة نصر",
    "city_en": "Nasr City",
    "name_ar": "مركز الجولف للعلاج الطبيعى",
    "name_en": "Golf Physiotherapy Center",
    "address_ar": "2شارع الفريق محمد ابراهيم متفرع من محمد حسنين هيكل - مدينة نصر",
    "address_en": "2 Al-Fareq Mohamed Ibrahim Street, off Mohamed Hassanein Heikal - Nasr City",
    "phone1": "02 22718800",
    "phone2": "012 02525252",
    "network": "Orange",
    "lat": 31.342686,
    "lng": 30.056616,
    "gmaps": "https://www.google.com/maps?q=31.342686,30.056616"
  },
  {
    "id": 110,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مدينة نصر",
    "city_en": "Nasr City",
    "name_ar": "مركز الفهد للعلاج الطبيعى - د. ايناس الحباك",
    "name_en": "Al Fahd Physiotheraby Center - Dr. Inas Al Habak",
    "address_ar": "52 ش نجاتى سراج / عماره 20 - المنطقه الثامنه - مدينة نصر",
    "address_en": "52 Nagaty Serag St., building # 20 - 8th. Area - Nasr City",
    "phone1": "01140830302",
    "phone2": "011 45440448",
    "network": "Orange",
    "lat": 31.35179,
    "lng": 30.046417,
    "gmaps": "https://www.google.com/maps?q=31.35179,30.046417"
  },
  {
    "id": 111,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مدينة نصر",
    "city_en": "Nasr City",
    "name_ar": "مركز طه كلينيك للعلاج الطبيعى",
    "name_en": "Taha Clinic Physiotherapy",
    "address_ar": "شارع أفريقيا امتداد مصطفى النحاس - عمارة 13 بلوك 34 - أعلى بيتزا هت - مدينة نصر",
    "address_en": "Africa Street, extension of Mustafa El Nahas - Building 13, Block 34 - Above Pizza Hut - Nasr City",
    "phone1": "01500556544",
    "phone2": "01031618825",
    "network": "Orange",
    "lat": 31.338505,
    "lng": 30.055988,
    "gmaps": "https://www.google.com/maps?q=31.338505,30.055988"
  },
  {
    "id": 112,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مدينة نصر",
    "city_en": "Nasr City",
    "name_ar": "مركز فيزيوفيرست للعلاج الطبيعى",
    "name_en": "Physiofirst Physical Therapy Center",
    "address_ar": "65نبيل الوقاد - أرض الجولف - مدينة نصر",
    "address_en": "65 Nabil Al-Waqqad - Ard Al-Golf - Nasr City",
    "phone1": "010 18800080",
    "phone2": "015 51864244",
    "network": "Orange",
    "lat": 31.392921,
    "lng": 30.054976,
    "gmaps": "https://www.google.com/maps?q=31.392921,30.054976"
  },
  {
    "id": 113,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مدينة نصر",
    "city_en": "Nasr City",
    "name_ar": "مركز لايف سبورت للعلاج الطبيعى",
    "name_en": "Life Physiotheraby center",
    "address_ar": "3شارع عبد المنعم الحسينىمن أحمد فؤاد نسيم من يوسف عباس",
    "address_en": "3 Abdel Moneim El-Husseini Street, off Ahmed Fouad Nassim Street, off Youssef Abbas Street",
    "phone1": "01206002002 - 010060",
    "phone2": "010 65953333",
    "network": "Orange",
    "lat": 31.318226,
    "lng": 30.07539,
    "gmaps": "https://www.google.com/maps?q=31.318226,30.07539"
  },
  {
    "id": 114,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مصر الجديدة",
    "city_en": "Heliopolis",
    "name_ar": "المركز الدولى للعلاج الطبيعى وعلاج الالام",
    "name_en": "International Physical Therapy Center & Pain Management",
    "address_ar": "ابراج عثمان – برج أ – روكسى – مصر الجديدة",
    "address_en": "1 Othman Towers, Tower A ,Roxy , Heliopolis",
    "phone1": "02 24537001-2-3-4-5",
    "phone2": "012 01111211",
    "network": "Orange",
    "lat": 31.315744,
    "lng": 30.0945,
    "gmaps": "https://www.google.com/maps?q=31.315744,30.0945"
  },
  {
    "id": 115,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مصر الجديدة",
    "city_en": "Heliopolis",
    "name_ar": "مركز الجولف للعلاج الطبيعى",
    "name_en": "Golf Physiotherapy Center",
    "address_ar": "9شارع الشهيد جلال حجاج متفرع من شارع أحمد تيسير - أرض الجولف - مصر الجديدة",
    "address_en": "9 Martyr Jalal Hajjaj Street, parts of Ahmed Tayseer Street - Ard El Golf - Heliopolis",
    "phone1": "02 22903777",
    "phone2": "01272666111",
    "network": "Orange",
    "lat": 31.325808,
    "lng": 30.081644,
    "gmaps": "https://www.google.com/maps?q=31.325808,30.081644"
  },
  {
    "id": 116,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مصر الجديدة",
    "city_en": "Heliopolis",
    "name_ar": "مركز الحياة شيراتون للعلاج الطبيعى و التاهيل",
    "name_en": "Al Hayat Sheraton Center for Physiotherapy",
    "address_ar": "98 ش سيد زكريا - مساكن شيراتون المطار - القاهره",
    "address_en": "98 Sayed Zakria St., Sheraton Building, Cairo Airport.",
    "phone1": "02 22679540",
    "phone2": "010 17855517",
    "network": "Orange",
    "lat": 31.371563,
    "lng": 30.104563,
    "gmaps": "https://www.google.com/maps?q=31.371563,30.104563"
  },
  {
    "id": 117,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مصر الجديدة",
    "city_en": "Heliopolis",
    "name_ar": "مركز الفيروز لجراحة الاسنان و العلاج الطبيعى",
    "name_en": "Al Fayrouz Center For Dental & Physiotherapy",
    "address_ar": "Nyoum Medical امام أكاديمية الشرطة بجوار لولو ماركت وبورتو كايرو",
    "address_en": "Historian Mohamed Refaat Street - in front of Shabrawy -",
    "phone1": "02 26209765",
    "phone2": "01288550221",
    "network": "Orange",
    "lat": 31.335167,
    "lng": 29.981964,
    "gmaps": "https://www.google.com/maps?q=31.335167,29.981964"
  },
  {
    "id": 118,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "مصر الجديدة",
    "city_en": "Heliopolis",
    "name_ar": "مركز فيزيوفيرست للعلاج الطبيعى",
    "name_en": "Physiofirst Physical Therapy Center",
    "address_ar": "مول كايرو كومبكس - داخل جولدز جيم - شارع أنقرة - شيراتون",
    "address_en": "Cairo Compex Mall - inside Gold's Gym - Ankara Street - Sheraton",
    "phone1": "010 18800080",
    "phone2": "015 51864244",
    "network": "Orange",
    "lat": 31.33806,
    "lng": 30.081532,
    "gmaps": "https://www.google.com/maps?q=31.33806,30.081532"
  },
  {
    "id": 119,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "وسط البلد",
    "city_en": "Down Town",
    "name_ar": "المركز الطبى للعلاج الطبيعى د. على حسن توفيق",
    "name_en": "Medical Center For Physiotherapy",
    "address_ar": "فى3 شارع رشدى - باب اللوق",
    "address_en": "3 Roshdy St, Bab El Louk",
    "phone1": "02 23939440",
    "phone2": "",
    "network": "Orange",
    "lat": 31.532696,
    "lng": 30.000273,
    "gmaps": "https://www.google.com/maps?q=31.532696,30.000273"
  },
  {
    "id": 120,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "وسط البلد",
    "city_en": "Down Town",
    "name_ar": "مركز الزايد للعلاج الطبيعى د. زايد عبد الرحيم محمد",
    "name_en": "Al Zayed Physiotheraby center - Dr. A. Rehim Zayed",
    "address_ar": "6 شارع عدلى – عمارات مصر للطيران – ميدان الأوبرا",
    "address_en": "6 Adly st., - Egypt Air Buildings – Opera Square",
    "phone1": "02 23957797",
    "phone2": "",
    "network": "Orange",
    "lat": 31.24561,
    "lng": 30.05089,
    "gmaps": "https://www.google.com/maps?q=31.24561,30.05089"
  },
  {
    "id": 121,
    "governorate_ar": "القاهرة",
    "governorate_en": "Cairo",
    "city_ar": "وسط البلد",
    "city_en": "Down Town",
    "name_ar": "مركز د.اسماعيل الخشاب",
    "name_en": "Dr.EsmaiAl Al Khashab Center",
    "address_ar": "5 شارع الجمهورية - تقاطع شارع حسن الاكبر - عابدين",
    "address_en": "5 Al Gomhoria St, From Hassan Al Akbar St, Aabdin",
    "phone1": "02 23909509",
    "phone2": "01004915596",
    "network": "Orange",
    "lat": 31.249262,
    "lng": 30.044996,
    "gmaps": "https://www.google.com/maps?q=31.249262,30.044996"
  },
  {
    "id": 122,
    "governorate_ar": "القليوبية",
    "governorate_en": "Qalubiya",
    "city_ar": "العبور",
    "city_en": "Al Obour",
    "name_ar": "مركز لايف سبورت للعلاج الطبيعى",
    "name_en": "Life Physiotheraby center",
    "address_ar": "مول كريتيف - أمام محكمة العبور - الحى الأول",
    "address_en": "Creative Mall - in front of the Obour Court - First District",
    "phone1": "01206002002 - 010060",
    "phone2": "010 65953333",
    "network": "Orange",
    "lat": 31.481781,
    "lng": 30.247387,
    "gmaps": "https://www.google.com/maps?q=31.481781,30.247387"
  },
  {
    "id": 123,
    "governorate_ar": "القليوبية",
    "governorate_en": "Qalubiya",
    "city_ar": "القليوبية",
    "city_en": "Qalubiya",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "الحي الخامس - 12 ش سميرة موسي - بجوار الشركة الزراعية - بجوار سوبر ماركت المالكى",
    "address_en": "5th District – 12 Samira Moussa Street – Next to the Agricultural Company – Beside El Malaky Supermarket",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.133974,
    "lng": 31.509886,
    "gmaps": "https://www.google.com/maps?q=30.133974,31.509886"
  },
  {
    "id": 124,
    "governorate_ar": "القليوبية",
    "governorate_en": "Qalubiya",
    "city_ar": "بنها",
    "city_en": "Banha",
    "name_ar": "مركز رويال سنتر للعلاج الطبيعى",
    "name_en": "Royal Center For Physiotherapy",
    "address_ar": "تقسيم عياد - امام النادى الرياضى",
    "address_en": "Taksim Ayad, In Front Of The Sprts Club",
    "phone1": "01228251727",
    "phone2": "",
    "network": "Orange",
    "lat": 31.198824,
    "lng": 30.478086,
    "gmaps": "https://www.google.com/maps?q=31.198824,30.478086"
  },
  {
    "id": 125,
    "governorate_ar": "القليوبية",
    "governorate_en": "Qalubiya",
    "city_ar": "شبرا الخيمة",
    "city_en": "Shubra Al Kheima",
    "name_ar": "مركز البرج للعلاج الطبيعى",
    "name_en": "Al borg physiotherapy",
    "address_ar": "برج سيتى مول شارع 15 مايو ناصية أحمد عرابى - شبرا الخيمة",
    "address_en": "City Mall Tower, 15th of May Street, corner of Ahmed Orabi, Shubra El Kheima",
    "phone1": "02 42201022",
    "phone2": "011 12777815",
    "network": "Orange",
    "lat": 31.25123,
    "lng": 30.121962,
    "gmaps": "https://www.google.com/maps?q=31.25123,30.121962"
  },
  {
    "id": 126,
    "governorate_ar": "القليوبية",
    "governorate_en": "Qalubiya",
    "city_ar": "شبين القناطر",
    "city_en": "Shibin Al Qanatir",
    "name_ar": "د/ عاطف محمود عبد الحميد الشيمى",
    "name_en": "Dr Atef Mahmoud Abdel Hamid AlShimy",
    "address_ar": "بجوار مستشفى المهدى - شبين القناطر",
    "address_en": "Next to Al-Mahdi Hospital - Shebin El Qanater",
    "phone1": "01002545058",
    "phone2": "",
    "network": "Orange",
    "lat": 31.316,
    "lng": 30.312325,
    "gmaps": "https://www.google.com/maps?q=31.316,30.312325"
  },
  {
    "id": 127,
    "governorate_ar": "القليوبية",
    "governorate_en": "Qalubiya",
    "city_ar": "قليوب",
    "city_en": "Qalub",
    "name_ar": "مركز العلاج الطبيعى الحديث (د. احمد سلامة)",
    "name_en": "Modern Physiotherapy Center",
    "address_ar": "شارع الساحة الشعبية - امام مدرسة التجارة - قليوب البلد",
    "address_en": "Al Saha Al Shabia Street",
    "phone1": "01002060051",
    "phone2": "",
    "network": "Orange",
    "lat": 31.215729,
    "lng": 30.178406,
    "gmaps": "https://www.google.com/maps?q=31.215729,30.178406"
  },
  {
    "id": 128,
    "governorate_ar": "المنوفية",
    "governorate_en": "Menoufia",
    "city_ar": "المنوفية",
    "city_en": "Menoufia",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "ش ياسين عبدالغفار - بجوار مستشفى الجامعة - برج الشامي - اعلى صيدلية الشامي - الدور الرابع",
    "address_en": "Yassin Abdel Ghaffar Street – Next to the University Hospital – Al Shami Tower – Above Al Shami Pharmacy – 4th Floor",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.575695,
    "lng": 31.012527,
    "gmaps": "https://www.google.com/maps?q=30.575695,31.012527"
  },
  {
    "id": 129,
    "governorate_ar": "المنوفية",
    "governorate_en": "Menoufia",
    "city_ar": "المنوفية",
    "city_en": "Menoufia",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "محور خدمات الحي الثاني - مــول اّل سعد - الدور الثانى - بجور شركة التشغيل والصيانة (شركة المياه) - أعلى صيدلية ابو زيد وسنتر مكة",
    "address_en": "Service of the 2nd District – Al Saad Mall – 2nd Floor – Next to the Operations & Maintenance Company (Water Company) – Above Abu Zeid Pharmacy and Mecca Center",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 30.364445,
    "lng": 30.509222,
    "gmaps": "https://www.google.com/maps?q=30.364445,30.509222"
  },
  {
    "id": 130,
    "governorate_ar": "المنوفية",
    "governorate_en": "Menoufia",
    "city_ar": "بركة السبع",
    "city_en": "Barakat Al Sabaa",
    "name_ar": "مركز النور للعلاج الطبيعى",
    "name_en": "Al Nour Physiotherapy Center",
    "address_ar": "شارع الشهيد فكرى - بركة السبع - المنوفية",
    "address_en": "Martyr Fikry Street - Berket El Sabaa - Menoufia",
    "phone1": "012 28602847",
    "phone2": "",
    "network": "Orange",
    "lat": 31.1126,
    "lng": 30.661942,
    "gmaps": "https://www.google.com/maps?q=31.1126,30.661942"
  },
  {
    "id": 131,
    "governorate_ar": "المنوفية",
    "governorate_en": "Menoufia",
    "city_ar": "شبين الكوم",
    "city_en": "Shibin Al Kom",
    "name_ar": "المركز الدولى للعلاج الطبيعى - شبين الكوم",
    "name_en": "International Physical Therapy Center",
    "address_ar": "6 ش تقسيم الشرطه - الأستاد الرياضى - عماره بيبرس - خلف مسجد المغفره - شبين الكوم",
    "address_en": "6 Takseem El Shorta - Bahry St., El Estad El Riady - Bebuers",
    "phone1": "01001114646",
    "phone2": "048 21316289",
    "network": "Orange",
    "lat": 31.008385,
    "lng": 30.56619,
    "gmaps": "https://www.google.com/maps?q=31.008385,30.56619"
  },
  {
    "id": 132,
    "governorate_ar": "المنوفية",
    "governorate_en": "Menoufia",
    "city_ar": "قويسنا",
    "city_en": "Quesna",
    "name_ar": "مركز روان للعلاج الطبيعى",
    "name_en": "Rawan Center",
    "address_ar": "شارع الصلايبة بجوار صيدلية أشرف - قويسنا",
    "address_en": "Al-Saliba Street, next to Ashraf Pharmacy - Quesna",
    "phone1": "012 23674916",
    "phone2": "011 19092772",
    "network": "Orange",
    "lat": 31.263577,
    "lng": 30.712904,
    "gmaps": "https://www.google.com/maps?q=31.263577,30.712904"
  },
  {
    "id": 133,
    "governorate_ar": "بنى سويف",
    "governorate_en": "Beni Suef",
    "city_ar": "ببا",
    "city_en": "Beba",
    "name_ar": "مركز الفتح للعلاج الطبيعى",
    "name_en": "El-Fatth Physiotherapy Center",
    "address_ar": "شارع صلاح الدين - بجوار صيدلية التقوى",
    "address_en": "Salah El Deen St,",
    "phone1": "01005382081",
    "phone2": "",
    "network": "Orange",
    "lat": 31.634344,
    "lng": 29.84446,
    "gmaps": "https://www.google.com/maps?q=31.634344,29.84446"
  },
  {
    "id": 134,
    "governorate_ar": "بنى سويف",
    "governorate_en": "Beni Suef",
    "city_ar": "بنى سويف",
    "city_en": "Beni Suef",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "(مركز الشفاء) ش الكورنيش برج الغزالى - بجوار مطعم الزاوى - الدور الاول علوى - أعلى صالون شاركس",
    "address_en": "(Al-Shifa Center) Corniche Street – Al-Ghazaly Tower – Next to Al Zawy Restaurant – 1st Floor (Upper Ground) – Above Sharks Salon",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 29.075333,
    "lng": 31.115168,
    "gmaps": "https://www.google.com/maps?q=29.075333,31.115168"
  },
  {
    "id": 135,
    "governorate_ar": "بنى سويف",
    "governorate_en": "Beni Suef",
    "city_ar": "بنى سويف",
    "city_en": "Beni Suef",
    "name_ar": "مركز الشريف للعلاج الطبيعى",
    "name_en": "Al Shrief Physiotherapy Center",
    "address_ar": "شارع سعد زغلول - بجوار معمل البرج",
    "address_en": "Saad Zagloul St,",
    "phone1": "01222593311",
    "phone2": "",
    "network": "Orange",
    "lat": 31.10018,
    "lng": 29.079939,
    "gmaps": "https://www.google.com/maps?q=31.10018,29.079939"
  },
  {
    "id": 136,
    "governorate_ar": "بنى سويف",
    "governorate_en": "Beni Suef",
    "city_ar": "بنى سويف",
    "city_en": "Beni Suef",
    "name_ar": "مركز لايف سبورت للعلاج الطبيعى",
    "name_en": "Life Sport Physiotherapy Center",
    "address_ar": "ميدان الزراعيين - برج الشيمى الطبى",
    "address_en": "Agricultural Square - Al-Shimi Medical Tower",
    "phone1": "01206002002 - 010060",
    "phone2": "010 65953333",
    "network": "Orange",
    "lat": 31.100779,
    "lng": 29.07044,
    "gmaps": "https://www.google.com/maps?q=31.100779,29.07044"
  },
  {
    "id": 137,
    "governorate_ar": "بورسعيد",
    "governorate_en": "Port Said",
    "city_ar": "بورسعيد",
    "city_en": "Port Said",
    "name_ar": "مركز التوحيد للعلاج الطبيعى",
    "name_en": "Al Tawheed Center for Phidothearaby",
    "address_ar": "برج التوحيد – شارع محمد على والنيل",
    "address_en": "El Tawheed Tower, Mohamed Ali and Nile st.,",
    "phone1": "0663240485",
    "phone2": "",
    "network": "Orange",
    "lat": 31.261272,
    "lng": 32.300983,
    "gmaps": "https://www.google.com/maps?q=32.300983,31.261272"
  },
  {
    "id": 138,
    "governorate_ar": "بورسعيد",
    "governorate_en": "Port Said",
    "city_ar": "بورسعيد",
    "city_en": "Port Said",
    "name_ar": "مركز الفيروز لجراحة الاسنان و العلاج الطبيعى",
    "name_en": "Al Fayrouz Center For Dental & Physiotherapy",
    "address_ar": "شارع 23 يوليو وصلاح الدين - بجوار مسجد لطفى شبارة",
    "address_en": "July 23 and Salah El Din Street - next to Lotfi Shabara Mosque",
    "phone1": "066 3248248",
    "phone2": "01288550223",
    "network": "Orange",
    "lat": null,
    "lng": null,
    "gmaps": ""
  },
  {
    "id": 139,
    "governorate_ar": "دمياط",
    "governorate_en": "Damietta",
    "city_ar": "دمياط الجديدة",
    "city_en": "New Damietta",
    "name_ar": "مركز الفيروز لجراحة الاسنان و العلاج الطبيعى",
    "name_en": "Al Fayrouz Center For Dental & Physiotherapy",
    "address_ar": "المركزيه (أ) خلف البنك الأهلى القديم - أمام المجمع الأسلامى",
    "address_en": "Central (A) behind the old National Bank - in front of the",
    "phone1": "01288550228",
    "phone2": "",
    "network": "Orange",
    "lat": null,
    "lng": null,
    "gmaps": ""
  },
  {
    "id": 140,
    "governorate_ar": "قنا",
    "governorate_en": "Qena",
    "city_ar": "قنا",
    "city_en": "Qena",
    "name_ar": "مركز الفيروز لجراحة الاسنان و العلاج الطبيعى",
    "name_en": "Al Fayrouz Center For Dental & Physiotherapy",
    "address_ar": "كورنيش النيل - أمام كوبرى دندره",
    "address_en": "Nile Corniche - in front of Dendera Bridge",
    "phone1": "012 81657148",
    "phone2": "",
    "network": "Orange",
    "lat": null,
    "lng": null,
    "gmaps": ""
  },
  {
    "id": 141,
    "governorate_ar": "دمياط",
    "governorate_en": "Damietta",
    "city_ar": "دمياط",
    "city_en": "Damietta",
    "name_ar": "الفا كير للعلاج الطبيعى",
    "name_en": "Alfa Care",
    "address_ar": "المركزيه خلف مطعم علي الفحم - أعلى قطونيل - الدور الأول - يوجد اسانسير",
    "address_en": "Central District – Behind “Ali Al-Fahm” Restaurant – Above Cottonil – 1st Floor – Elevator available",
    "phone1": "15662",
    "phone2": "",
    "network": "Orange",
    "lat": 31.436646,
    "lng": 31.677284,
    "gmaps": "https://www.google.com/maps?q=31.436646,31.677284"
  },
  {
    "id": 142,
    "governorate_ar": "سوهاج",
    "governorate_en": "Sohag",
    "city_ar": "سوهاج",
    "city_en": "Sohag",
    "name_ar": "المركز التخصصى للعلاج الطبيعى - د. اشرف مكرم",
    "name_en": "Dr. Ashraf Makram Physiotherapy center",
    "address_ar": "شارع الجلاء بجوار الجمعية الزراعية - المراغة",
    "address_en": "Al Jalaa Street, next to the Agricultural Association - Almuragha",
    "phone1": "093 2534480",
    "phone2": "011 44356060",
    "network": "Orange",
    "lat": 31.604479,
    "lng": 26.701967,
    "gmaps": "https://www.google.com/maps?q=31.604479,26.701967"
  },
  {
    "id": 143,
    "governorate_ar": "سوهاج",
    "governorate_en": "Sohag",
    "city_ar": "سوهاج",
    "city_en": "Sohag",
    "name_ar": "المركز التخصصى للعلاج الطبيعى - د. اشرف مكرم",
    "name_en": "Dr. Ashraf Makram Physiotherapy center",
    "address_ar": "شارع الجهاد من شارع الكاشف أمام مستشفى الحميات",
    "address_en": "Jihad Street from Al-Kashef Street in front of the Fever Hospital",
    "phone1": "093 2718660",
    "phone2": "011 0049211",
    "network": "Orange",
    "lat": 31.763702,
    "lng": 26.659405,
    "gmaps": "https://www.google.com/maps?q=31.763702,26.659405"
  },
  {
    "id": 144,
    "governorate_ar": "سوهاج",
    "governorate_en": "Sohag",
    "city_ar": "سوهاج",
    "city_en": "Sohag",
    "name_ar": "المركز التخصصى للعلاج الطبيعى - د. اشرف مكرم",
    "name_en": "Dr. Ashraf Makram Physiotherapy center",
    "address_ar": "شارع الثورة بجوار مخبز الراهب وصيدلية الخضيرى - طهطا",
    "address_en": "Al-Thawra Street, next to Al-Raheb Bakery and Al-Khudairi Pharmacy",
    "phone1": "093 4292615",
    "phone2": "015 50114113",
    "network": "Orange",
    "lat": 31.509579,
    "lng": 26.765617,
    "gmaps": "https://www.google.com/maps?q=31.509579,26.765617"
  }
];
